/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Configschema {
	/**
	 * Theme to be used in the graphical overlays; will use "red" if none supplied.
	 */
	theme: 'red' | 'green' | 'blue';
	obs: {
		enabled: boolean;
		url: string;
		password: string;
		names: {
			scenes: {
				gameLayout: string;
			};
			captures: {
				/**
				 * @minItems 1
				 */
				games: [string, ...string[]];
				camera: string;
			};
		};
	};
	foobar2000: {
		enabled: boolean;
		url: string;
		username: string;
		password: string;
	};
	xr18: {
		enabled: boolean;
		ip: string;
		fadeLength: number;
		faders: {
			player: string;
			reader: string;
			game: string;
		};
	};
	tracker: {
		enabled: boolean;
		useTestData: boolean;
		url: string;
		eventShort: string;
		currencySymbol: string;
	};
}
