/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Users = {
	name: string;
	pronouns?: string;
}[];

export interface Participants {
	commentators: Users;
	readers: Users;
}
